version: 0.2

phases: 
  install:
    commands:
    - echo Installing Node [14]
    - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
    - apt install -y nodejs
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - echo Installing npm 
    
    pre_build:
      commands: 
        - echo Installing dependencies
        - npm install
    build:
      commands:
        - echo Testing
        - npm tests
        - echo Building
        - npm build
artifacts: 
  files:S
   - "**/*"
   discard-paths: no
   base-directory: dist