version: 0.2

phases: 
  install:
    commands:
    - echo Installing Node [14]
    - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
    - apt install -y nodejs
    - echo Installing npm 
    - apt install -y npm
    pre_build:
      commands: 
    - echo Installing dependencies
    - npm install
    build:
      commands:
      - echo Testing
      - npm tests
      - echo Building
      - npm build
artifacts: 
  files:
   - "**/*"
   discard-paths: no
   base-directory: dist